# Generated by Django 4.2.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        # Removido model_name y context_used para evitar errores de columna duplicada
        migrations.AddField(
            model_name='message',
            name='processed_by_ollama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='ollama_model_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='preferred_model',
            field=models.CharField(default='llama2', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conversation_history_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OllamaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]