# Generated by Django 4.2 on 2025-04-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_ollama_integration'),
        ('chatbot', '0002_usuario'),
    ]

    operations = [
    ]
