# Generated by Django 4.2 on 2025-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='img',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('HOMBRE', 'Hombres'), ('MUJER', 'Mujeres'), ('NINO', 'Niños'), ('PRODUCTOS', 'Productos')], default='HOMBRE', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(default='imagenes/default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
