# Generated by Django 4.2 on 2025-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_transaccion_jugador_remove_producto_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('talla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMujer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edad_recomendada', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
